######################################################################
# Automatically generated by qmake (3.0) Fri Jun 24 15:18:33 2016
######################################################################

QT       = core
TEMPLATE = app
TARGET = tadaridaD
INCLUDEPATH += "include"

CONFIG += link_pkgconfig
PKGCONFIG += fftw3f sndfile

# Input
HEADERS += include/*.h
SOURCES += *.cpp
#SOURCES += detec.cpp deteclaunch.cpp detectreatment.cpp main.cpp

# Cleanup
QMAKE_CLEAN += tadaridaD
